spring:
  datasource:
    hikari:
      maximum-pool-size: 25
      minimum-idle: 1
    driver-class-name: org.firebirdsql.jdbc.FBDriver
    initialization-mode: always
    continue-on-error: true

  jpa:
    database-platform: org.hibernate.dialect.FirebirdDialect
    show-sql: true
    properties.hibernate.format_sql: true
    hibernate:
      ddl-auto: none

  liquibase.change-log: classpath:db/changelog/db.changelog-master.xml

  data:
    rest:
      basePath: /api

keycloak:
  auth-server-url: "http://${KEYCLOAK_URL}:${KEYCLOAK_PORT}/auth"
  realm: clematis
  resource: clematis-money-tracker-api
  bearer-only: true

logging:
  file:
    path:
      ${LOGGING_PATH}
