spring:
  datasource:
    hikari:
      maximum-pool-size: 25
      minimum-idle: 1
    driver-class-name: org.firebirdsql.jdbc.FBDriver
    initialization-mode: always

  jpa:
    database-platform: org.hibernate.dialect.FirebirdDialect
    hibernate.ddl-auto: update
    show-sql: true
    properties.hibernate.format_sql: true

  liquibase.change-log: classpath:db/changelog/db.changelog-master.xml

  data:
    rest:
      basePath: /api

keycloak:
  realm: clematis
  bearer-only: true
  auth-server-url: "http://${KEYCLOAK_URL}:${KEYCLOAK_PORT}/auth"
  resource: client
  principal-attribute: preferred_username

logging:
  file:
    path:
      ${LOGGING_PATH}
