management:
  endpoints:
    jmx:
      exposure:
        include: "health,info,env,beans"
    web:
      exposure:
        include: "health,info,env,beans"

spring:

  auth:
    authServer: "http://${KEYCLOAK_URL}:${KEYCLOAK_PORT}/realms/${keycloak.realm}/protocol/openid-connect"
    clientSecret: ${KEYCLOAK_SECRET}

  datasource:
    hikari:
      maximum-pool-size: 25
      minimum-idle: 1
    driver-class-name: org.firebirdsql.jdbc.FBDriver

  jpa:
    database-platform: org.hibernate.dialect.FirebirdDialect
    show-sql: true
    hibernate:
      ddl-auto: none

  data:
    rest:
      basePath: /api

  sql:
    init:
      mode: always
      separator: ^
      continue-on-error: true

  jmx:
    enabled: true
    url: service:jmx:jmxmp://${JMXMP_HOST}:${JMXMP_PORT}/

keycloak:
  auth-server-url: "http://${KEYCLOAK_URL}:${KEYCLOAK_PORT}/auth"
  realm: clematis
  resource: ${KEYCLOAK_CLIENT}
  bearer-only: true
  cors: true

logging:
  file:
    path:
      ${LOG_PATH}

springdoc:
  swagger-ui:
    display-request-duration: true
    groups-order: ASC
    operationsSorter: method
    disable-swagger-default-url: true
    use-root-path: true
  show-actuator: true