management:
  endpoints:
    jmx:
      exposure:
        include: "health,info,env,beans"
    web:
      exposure:
        include: "health,info,env,beans"

server:
  forward-headers-strategy: framework

spring:

  auth:
    authServer: "${KEYCLOAK_URL}:${KEYCLOAK_PORT}/realms/${keycloak.realm}/protocol/openid-connect"
    clientSecret: ${KEYCLOAK_SECRET}

  datasource:
    hikari:
      maximum-pool-size: 25
      minimum-idle: 1
    driver-class-name: org.firebirdsql.jdbc.FBDriver

  jpa:
    database-platform: org.hibernate.community.dialect.FirebirdDialect
    show-sql: true
    hibernate:
      ddl-auto: none
      jdbc:
        use_scrollable_resultset: false
    properties:
      hibernate:
        format_sql: true
        jdbc:
          use_scrollable_resultset: false
          fetch_size: 50
        connection:
          wrap_result_sets: true
        query:
          result_type: FORWARD_ONLY

  data:
    rest:
      basePath: /api

  sql:
    init:
      mode: always
      separator: ^
      continue-on-error: true

  jmx:
    enabled: true
    url: service:jmx:jmxmp://${JMXMP_HOST}:${JMXMP_PORT}/

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "${KEYCLOAK_URL}:${KEYCLOAK_PORT}/realms/clematis"
          jwk-set-uri: "${KEYCLOAK_URL}:${KEYCLOAK_PORT}/realms/clematis/protocol/openid-connect/certs"

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
  file:
    path:
      ${LOG_PATH}

springdoc:
  swagger-ui:
    display-request-duration: true
    groups-order: ASC
    operationsSorter: method
    disable-swagger-default-url: true
    use-root-path: true
  show-actuator: true
