version: '3.7'

services:
  money_tracker_api:
      image: atroshin/clematis.mt.api:0.0.2-SNAPSHOT
      networks:
        - clematis
      ports:
        - "18085:8080"
      env_file:
        - money_tracker_api.env
      volumes:
        - ../logs:/var/log/clematis

networks:
  clematis:
    driver: bridge
