version: '3.7'

services:
  money_tracker_api:
      image: clematis.mt.api:latest
      networks:
        - clematis
      ports:
        - "18085:8080"
      env_file:
        - money_tracker_api.local.env
      volumes:
        - ../log:/var/log/clematis

  money_tracker_db:
       image: jacobalberty/firebird:2.5.9-sc
       networks:
         - clematis
       env_file:
         - money_tracker_api.local.env
       volumes:
         - ../src/test/resources:/firebird/data
       ports:
         - "3050:3050"

networks:
  clematis:
    driver: bridge
