version: '3.7'

services:
  money-tracker-api:
    container_name: clematis-money-tracker-api
    image: clematis.mt.api:latest
    networks:
      - clematis
    env_file:
      - .env
    ports:
      - ${SPRING_LOCAL_PORT}:${SPRING_DOCKER_PORT}
      - "15085:5000"
      - "15086:5001"
    volumes:
      - /home/clematis/mt/logs:/var/log/clematis
    restart: unless-stopped
    depends_on:
      money-tracker-db:
        condition: service_healthy

  money-tracker-api-demo:
    container_name: clematis-money-tracker-api-demo
    image: clematis.mt.api:latest
    networks:
      - clematis
    env_file:
      - .env.demo
    ports:
      - ${SPRING_LOCAL_PORT}:${SPRING_DOCKER_PORT}
      - "15087:5000"
      - "15088:5001"
    environment:
      - "SPRING_PROFILES_ACTIVE=local"
    volumes:
      - /home/clematis/mt-demo/logs:/var/log/clematis
    restart: unless-stopped
    depends_on:
      money-tracker-db:
        condition: service_healthy

  money-tracker-db:
    container_name: clematis-money-tracker-db
    image: jacobalberty/firebird:2.5.9-sc
    networks:
      - clematis
    ports:
      - "3050:3050"
    env_file:
      - money_tracker_server.env
    volumes:
      - /home/firebird/db:/firebird/data
    restart: unless-stopped

  money-tracker-db-demo:
    container_name: clematis-money-tracker-db-demo
    image: jacobalberty/firebird:2.5.9-sc
    networks:
      - clematis
    ports:
      - "3051:3050"
    env_file:
      - money_tracker_server.env
    volumes:
      - /home/firebird/demo/db:/firebird/data
    restart: unless-stopped

networks:
  clematis:
    driver: bridge
