services:
  money-tracker-api:
    container_name: clematis-money-tracker-api
    image: clematis.mt.api:latest
    networks:
      - clematis_mt
    ports:
      - "18085:8080"
      - "15085:5000"
      - "15086:5001"
    env_file:
      - money_tracker_api.env
    volumes:
      - /home/firebird/logs:/var/log/clematis
    restart: unless-stopped
    depends_on:
      money-tracker-db:
        condition: service_healthy

  money-tracker-db:
    container_name: clematis-money-tracker-db
    image: jacobalberty/firebird:2.5.9-sc
    networks:
      - clematis_mt
    ports:
      - "3050:3050"
    env_file:
      - money_tracker_server.env
    volumes:
      - /home/firebird/db:/firebird/data
    restart: unless-stopped

networks:
  clematis_mt:
    driver: bridge
