CREATE
OR ALTER
VIEW ACCOUNTS_OPERATIONS (NAME, TRANSFERDATE, AMOUNT, CURRENCY)
AS
SELECT acc.NAME, TRANSFERDATE, ROUND(AMOUNT * MONEY_SIGN, 2), CODE
FROM ALL_OPERATIONS_HISTORY
         JOIN ACCOUNT AS acc ON acc.ID = acc_id
         JOIN MONEYTYPE AS mt ON acc.MONEYTYPE = mt.ID
ORDER BY TRANSFERDATE;