CREATE OR ALTER VIEW COMMODITIES_BUCKET_PER_MONTH (YEARE, MONTHE, COMMODITIES)
AS
SELECT
    EXTRACT(YEAR FROM EXPENSEITEM.TRANSFERDATE) as YEARE,
    EXTRACT(MONTH FROM EXPENSEITEM.TRANSFERDATE) as MONTHE,
    COUNT(DISTINCT(EXPENSEITEM.COMM)) AS COMMODITIES

FROM EXPENSEITEM
GROUP BY YEARE, MONTHE;

----------------------------------------------------------

CREATE OR ALTER VIEW LAST_COMMODITIES_PER_MONTH (YEARE, MONTHE, COMMODITIES)
AS
SELECT
    EXTRACT(YEAR FROM LAST_COMMODITIES_VIEW.TRANSACTION_DATE) as YEARE,
    EXTRACT(MONTH FROM LAST_COMMODITIES_VIEW.TRANSACTION_DATE) as MONTHE,
    COUNT(*) AS COMMODITIES

FROM LAST_COMMODITIES_VIEW
GROUP BY YEARE, MONTHE;